id: I3E271E63
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T12:13:25+00:00'
last_modified: '2022-06-08T14:05:57.633287+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4687
  title: དཔྱད་རྩོམ་བློ་གསལ་མགུལ་རྒྱན།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    664F:
      image_group_id: I3CN4689
      title: ''
      total_pages: 235
      order: 1
      base_file: 664F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
