id: P010506
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-19 20:53:14.975749
source_metadata:
  id: bdr:W3CN4687
  title: དཔྱད་རྩོམ་བློ་གསལ་མགུལ་རྒྱན།
  author: ''
  volumes:
    8882fae832c8406ab9e2657ad5456de7:
      image_group_id: I3CN4689
      title: ''
      volume_number: 1
      total_pages: 235
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
